from registry.saas.hand-china.com/hap-cloud/base:latest

copy ./Exam1/target/Exam1.jar Exam1.jar

copy ./Exam2/target/Exam2.jar Exam2.jar

java -cp Exam1.jar com.hand.Test 1;

java -cp Exam2.jar com.hand.Test 1;